@host = http://localhost:8080
POST {{host}}/user
Content-Type: application/json

{
    "name": "ahmad123",
    "email": "ahmad123@example.com",
    "password": "ahmad123"
}

###
POST {{host}}/user/login
Content-Type: application/json

{
    "email": ".ahmad123@example.com",
    "password": "ahmad123"
}

###
GET {{host}}/users?page=5&limit=15


###
GET {{host}}/user?name=karl markx

###
GET {{host}}/user/14

###
PUT {{host}}/user/15
Content-Type: application/json

{
    "Name": "update",
    "Email": "update@example.com"
}
###

DELETE {{host}}/user/13